import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  th: {
    // Nav
    home: 'หน้าแรก',
    findJobs: 'ค้นหางาน',
    employerPortal: 'ผู้ประกอบการ',
    login: 'เข้าสู่ระบบ',
    register: 'สมัครสมาชิก',
    logout: 'ออกจากระบบ',
    dashboard: 'แดชบอร์ด',
    createJob: 'ลงประกาศงาน',
    history: 'ประวัติประกาศงาน',
    pricing: 'ราคาและแพ็กเกจ',
    seekerPortal: 'ผู้หางาน',
    langToggle: 'EN',

    // Home
    heroTitle: 'ค้นพบอาชีพในฝันของคุณที่นี่',
    heroSubtitle: 'รวบรวมงานจากบริษัทชั้นนำทั่วประเทศ อัปเดตใหม่ทุกวัน',
    searchPlaceholder: 'ชื่อตำแหน่งงาน, บริษัท, หรือคีย์เวิร์ด...',
    searchBtn: 'ค้นหางาน',
    popularSearches: 'คำค้นหายอดนิยม:',
    recentJobs: 'งานล่าสุดที่คุณอาจสนใจ',
    viewDetails: 'ดูรายละเอียด',
    fullTime: 'งานประจำ',
    partTime: 'งานพาร์ทไทม์',
    contract: 'สัญญาจ้าง',
    internship: 'ฝึกงาน',

    // Search
    searchTitle: 'ผลการค้นหางาน',
    filterTitle: 'ตัวกรองข้อมูล',
    filterLocation: 'สถานที่ปฏิบัติงาน',
    filterCategory: 'หมวดหมู่งาน',
    filterWorkType: 'ประเภทการทำงาน',
    filterSalary: 'เงินเดือนขั้นต่ำ (บาท)',
    all: 'ทั้งหมด',
    applyBtn: 'สมัครงาน',
    noJobsFound: 'ไม่พบงานที่ตรงกับการค้นหาของคุณ',
    expectedSalary: 'เงินเดือนคาดหวัง',
    salaryUnit: 'บาท / เดือน',

    // Job Details
    jobDescription: 'รายละเอียดงาน',
    requirements: 'คุณสมบัติผู้สมัคร',
    salary: 'เงินเดือน',
    negotiable: 'ตามตกลง',
    postedDate: 'โพสต์เมื่อ',
    backToSearch: 'กลับไปหน้าค้นหา',
    aboutCompany: 'เกี่ยวกับบริษัท',
    viewCompanyProfile: 'ดูโปรไฟล์บริษัท',
    salaryRange: 'ช่วงเงินเดือน',

    // Employer Dashboard
    activeJobs: 'งานที่กำลังเปิดรับ',
    totalApplicants: 'ผู้สมัครทั้งหมด',
    interviews: 'นัดสัมภาษณ์แล้ว',
    statsSummary: 'ภาพรวมสถิติประกาศงานของคุณ',
    manageJobs: 'จัดการประกาศงานของคุณ',
    jobTitle: 'ชื่อตำแหน่ง',
    applicantsCount: 'จำนวนผู้สมัคร',
    status: 'สถานะ',
    actions: 'ดำเนินการ',
    viewApplicants: 'ดูผู้สมัคร',
    dashboardOverview: 'แผงควบคุมหลัก',
    unreadMessages: 'ข้อความที่ยังไม่ได้อ่าน',

    // Employer Applications
    applicantsFor: 'ผู้สมัครสำหรับตำแหน่ง',
    applicantName: 'ชื่อผู้สมัคร',
    applicantEmail: 'อีเมลติดต่อ',
    applicationDate: 'วันที่สมัคร',
    resumeTitle: 'ใบสมัคร / เรซูเม่',
    changeStatus: 'เปลี่ยนสถานะ',
    statusPending: 'รอการพิจารณา',
    statusInterview: 'นัดสัมภาษณ์',
    statusRejected: 'ปฏิเสธ',
    noApplicants: 'ยังไม่มีผู้สมัครสำหรับงานนี้',
    viewResumeBtn: 'เปิดดูเรซูเม่',
    closeModal: 'ปิดหน้าต่าง',

    // Seeker Login/Register
    loginTitleSeeker: 'เข้าสู่ระบบ (ผู้หางาน)',
    registerTitleSeeker: 'สมัครสมาชิก (ผู้หางาน)',
    loginTitleEmployer: 'เข้าสู่ระบบ (ผู้ประกอบการ)',
    registerTitleEmployer: 'สมัครสมาชิก (ผู้ประกอบการ)',
    username: 'ชื่อผู้ใช้งาน',
    password: 'รหัสผ่าน',
    emailLabel: 'อีเมล',
    fullNameLabel: 'ชื่อ-นามสกุล',
    companyLabel: 'ชื่อบริษัท',
    orLoginWith: 'หรือเข้าสู่ระบบด้วย',
    dontHaveAccount: 'ยังไม่มีบัญชีผู้ใช้?',
    alreadyHaveAccount: 'มีบัญชีผู้ใช้อยู่แล้ว?',
    registerLink: 'สมัครสมาชิกที่นี่',
    loginLink: 'เข้าสู่ระบบที่นี่',
    loginBtn: 'เข้าสู่ระบบ',
    registerBtn: 'สมัครสมาชิก',

    // Apply Wizard
    applyWizardTitle: 'สมัครงาน - กรอกข้อมูลใบสมัคร',
    wizardStep1: 'เลือกภาษาใบสมัคร',
    wizardStep2: 'กรอกข้อมูลเรซูเม่',
    wizardStep3: 'สมัครงานเสร็จสิ้น',
    thMode: 'ใบสมัครภาษาไทย (Thai Resume)',
    enMode: 'ใบสมัครภาษาอังกฤษ (English Resume)',
    thModeDesc: 'กรอกข้อมูลใบสมัครเป็นภาษาไทยเพื่อยื่นกับบริษัทในไทย',
    enModeDesc: 'กรอกข้อมูลใบสมัครเป็นภาษาอังกฤษเพื่อยื่นกับบริษัทต่างชาติหรือองค์กรชั้นนำ',
    next: 'ถัดไป',
    back: 'ย้อนกลับ',
    submitApplication: 'บันทึกและส่งใบสมัคร',
    personalInfo: 'ข้อมูลส่วนตัว',
    fullName: 'ชื่อ-นามสกุล',
    targetedJobTitle: 'ตำแหน่งงานที่คาดหวัง / จุดมุ่งหมาย',
    aboutMe: 'เกี่ยวกับฉัน (แนะนำตัวสั้นๆ)',
    contactInfo: 'ข้อมูลการติดต่อ',
    phone: 'เบอร์โทรศัพท์',
    address: 'ที่อยู่ปัจจุบัน',
    email: 'อีเมลสำหรับติดต่อ',
    socialProfiles: 'โปรไฟล์โซเชียล (ถ้ามี)',
    workExperience: 'ประวัติการทำงาน',
    company: 'บริษัท / องค์กร',
    position: 'ตำแหน่งงาน',
    duration: 'ระยะเวลา (เช่น 2023 - ปัจจุบัน)',
    workDesc: 'รายละเอียดงาน / ความรับผิดชอบ',
    addExperience: 'เพิ่มประวัติการทำงาน',
    education: 'ประวัติการศึกษา',
    school: 'สถานศึกษา / มหาวิทยาลัย',
    degree: 'วุฒิการศึกษา (เช่น ปริญญาตรี สาขาคอมพิวเตอร์)',
    gradYear: 'ปีที่จบการศึกษา',
    addEducation: 'เพิ่มประวัติการศึกษา',
    skills: 'ทักษะความสามารถ',
    techSkills: 'ทักษะเฉพาะทาง / เครื่องมือ (คั่นด้วยเครื่องหมายจุลภาค ,)',
    softSkills: 'ทักษะทางอารมณ์ / การทำงานร่วมกัน (คั่นด้วยเครื่องหมายจุลภาค ,)',
    languages: 'ความสามารถด้านภาษา',
    langLevel: 'ระดับความสามารถ (เช่น ดีเยี่ยม, พอใช้)',
    langRating: 'ระดับคะแนน (1-5 ดาว)',
    addLanguage: 'เพิ่มภาษา',
    saveProfileOnly: 'บันทึกโปรไฟล์เฉยๆ (ยังไม่ส่งสมัคร)',
    submitSuccess: 'ส่งใบสมัครเรียบร้อยแล้ว!',
    successDesc: 'ระบบได้ทำการบันทึกข้อมูลเรซูเม่ของคุณ และส่งใบสมัครงานนี้ไปยังนายจ้างเรียบร้อยแล้ว คุณสามารถรอการติดต่อกลับจากผู้ประกอบการได้โดยตรง',
    backToJobs: 'กลับไปหน้าค้นหาหลัก',

    // Employer Create Job
    postNewJob: 'ลงประกาศงานใหม่',
    postJobDesc: 'ระบุข้อมูลเกี่ยวกับตำแหน่งงาน สวัสดิการ และคุณสมบัติที่ต้องการให้ครบถ้วนเพื่อผลลัพธ์ที่ดีที่สุด',
    locationPlaceholder: 'เช่น กรุงเทพฯ, เชียงใหม่ (หรือ Remote)',
    departmentLabel: 'แผนก (ระบุหรือไม่ก็ได้)',
    salaryMinLabel: 'เงินเดือนขั้นต่ำ (บาท)',
    salaryMaxLabel: 'เงินเดือนสูงสุด (บาท)',
    workTypeLabel: 'ประเภทสถานที่ทำงาน',
    publishBtn: 'ลงประกาศงานทันที',
    saveDraftBtn: 'บันทึกแบบร่าง',
    categoryLabel: 'หมวดหมู่งาน',
    locationLabel: 'สถานที่ปฏิบัติงาน',
    descriptionLabel: 'รายละเอียดงาน / หน้าที่รับผิดชอบ',
    requirementsLabel: 'คุณสมบัติที่ต้องการ / ความสามารถ',
    successCreateJob: 'สร้างประกาศงานสำเร็จ!',

    // Employer History & Pricing
    historyTitle: 'ประวัติการประกาศงานทั้งหมด',
    active: 'กำลังเปิดรับสมัคร',
    draft: 'แบบร่าง',
    editBtn: 'แก้ไข',
    deleteBtn: 'ลบ',
    pricingTitle: 'ราคาและแพ็กเกจสำหรับนายจ้าง',
    pricingDesc: 'เลือกแผนที่เหมาะสมเพื่อหาบุคลากรที่ดีที่สุดสำหรับธุรกิจของคุณ',
    freePlan: 'แผนเริ่มต้น ฟรี',
    premiumPlan: 'แผนพรีเมียม',
    enterprisePlan: 'แผนองค์กร',
    priceFree: '฿0',
    pricePremium: '฿1,490',
    priceEnterprise: '฿4,900',
    priceUnit: '/ เดือน',
    choosePlan: 'เลือกแผนนี้',
    unlimitedJobs: 'ลงประกาศงานได้ไม่จำกัด',
    candidateMatch: 'ระบุผู้สมัครที่เหมาะสมที่สุด',
    statsView: 'ดูสถิติผู้เข้าชมแบบละเอียด',

    // Employer Dashboard Extras
    welcomeBack: 'ยินดีต้อนรับกลับมาคุณ ',
    recruitmentToday: 'นี่คือข้อมูลภาพรวมการสรรหาบุคลากรของคุณในวันนี้',
    totalActiveJobs: 'งานที่เปิดรับสมัครทั้งหมด',
    newApplicants7Days: 'ผู้สมัครรายใหม่ (7 วันที่ผ่านมา)',
    recentApplicantsTitle: 'ผู้สมัครล่าสุด',
    viewAll: 'ดูทั้งหมด',
    nameCol: 'ชื่อ',
    roleCol: 'ตำแหน่ง',
    dateCol: 'วันที่',
    hiringFunnelTitle: 'ขั้นตอนการจ้างงาน',
    appliedStage: 'สมัครแล้ว',
    screenedStage: 'คัดกรองแล้ว',
    interviewedStage: 'สัมภาษณ์แล้ว',
    offeredStage: 'เสนอจ้างแล้ว',
    quickActionsTitle: 'เมนูด่วน',
    postAJobBtn: 'ลงประกาศงาน',
    scheduleInterviewBtn: 'นัดสัมภาษณ์งาน',
    viewReportsBtn: 'ดูรายงานสถิติ',
    activePostingsTitle: 'ประกาศงานที่ใช้งานอยู่',
    noActiveJobsFound: 'ไม่พบงานที่เปิดใช้งานอยู่',
    applicantsCountUpper: 'ผู้สมัคร',
    interviewsCountUpper: 'นัดสัมภาษณ์',
    boostTitle: 'เพิ่มการเข้าถึงประกาศงาน',
    boostDesc: 'โปรโมตประกาศงานของคุณให้ผู้สมัครที่ตรงกลุ่มเป้าหมายเห็นมากขึ้น 3 เท่าด้วยฟีเจอร์พรีเมียมของเรา',
    exploreOptions: 'สำรวจสิทธิพิเศษเพิ่มเติม',

    // Employer Create Job Extras
    postNewJobTitle: 'ลงประกาศงานใหม่',
    postNewJobDesc: 'กรอกรายละเอียดเกี่ยวกับงาน ข้อกำหนด และสวัสดิการของตำแหน่งนี้',
    errorLabel: 'เกิดข้อผิดพลาด',
    basicDetails: 'ข้อมูลพื้นฐานของตำแหน่งงาน',
    jobTitleInput: 'ชื่อตำแหน่งงาน',
    jobTitlePlaceholder: 'เช่น นักพัฒนาซอฟต์แวร์อาวุโส',
    categoryInput: 'หมวดหมู่งาน',
    selectCategory: 'เลือกหมวดหมู่',
    locationInput: 'สถานที่ปฏิบัติงาน',
    locationInputPlaceholder: 'เช่น กรุงเทพมหานคร หรือ ทำงานแบบรีโมท',
    workTypeInput: 'รูปแบบการทำงาน',
    onSite: 'ปฏิบัติงานที่บริษัท (On-site)',
    hybridWork: 'ทำงานแบบไฮบริด (Hybrid Work)',
    remoteWork: 'ทำงานจากที่บ้าน (Work from Home)',
    minSalaryInput: 'เงินเดือนเริ่มต้น (บาท)',
    maxSalaryInput: 'เงินเดือนสูงสุด (บาท)',
    salaryMinPlaceholder: 'เช่น 30000',
    salaryMaxPlaceholder: 'เช่น 50000',
    descriptionAndRequirements: 'รายละเอียดงาน & คุณสมบัติ',
    jobDescriptionInput: 'รายละเอียดหน้าที่ความรับผิดชอบ',
    jobDescPlaceholder: 'อธิบายรายละเอียดงาน หน้าที่ความรับผิดชอบ และทีมงานของคุณ...',
    requirementsInput: 'คุณสมบัติผู้สมัคร',
    requirementsPlaceholder: 'ระบุทักษะ ประสบการณ์ และคุณสมบัติที่จำเป็นสำหรับงานนี้...',
    publishingLabel: 'กำลังดำเนินการ...',
    listingStatusTitle: 'สถานะประกาศงาน',
    draftBadge: 'แบบร่าง',
    draftStatusDesc: 'ประกาศงานนี้จะไม่แสดงให้ผู้สมัครเห็นจนกว่าคุณจะกดปุ่ม \'ลงประกาศงาน\'',
    proTipsTitle: 'เคล็ดลับการลงประกาศ',
    proTip1: 'ใช้ชื่อตำแหน่งงานที่สั้นและตรงประเด็นเพื่อดึงดูดผู้สมัครที่ตรงความสามารถที่สุด',
    proTip2: 'การระบุเงินเดือนจะช่วยเพิ่มจำนวนการส่งใบสมัครเฉลี่ยถึง 30%',
    proTip3: 'ระบุเฉพาะคุณสมบัติที่จำเป็นจริงๆ เพื่อเปิดโอกาสให้ผู้สมัครที่มีศักยภาพสูงสุด',

    // Employer History Extras
    jobPostingHistoryTitle: 'ประวัติการลงประกาศงาน',
    managePostingsDesc: 'จัดการข้อมูลและตรวจสอบสถิติการลงประกาศงานทั้งหมดของคุณ',
    postNewJobBtn: 'ลงประกาศงานใหม่',
    searchHistoryPlaceholder: 'ค้นหาด้วยชื่อตำแหน่งงาน หรือ สถานที่ปฏิบัติงาน...',
    filterBtn: 'ตัวกรอง',
    postedDateCol: 'วันที่ลงประกาศ',
    loadingJobsText: 'กำลังโหลดข้อมูลงาน...',
    noJobsHistoryFound: 'ไม่พบประกาศงานในประวัติของคุณ',
    confirmDeleteJob: 'คุณแน่ใจหรือไม่ว่าต้องการลบประกาศงานนี้?',

    // Employer Pricing Extras
    pricingHeaderTitle: 'เร่งการสรรหาบุคลากรที่มีคุณภาพ',
    pricingHeaderDesc: 'เลือกแผนการลงโฆษณาประกาศงานที่ตรงกับงบประมาณและความต้องการสรรหาของคุณ เพื่อติดต่อผู้สมัครที่ยอดเยี่ยมได้อย่างรวดเร็ว',
    basicPlanTitle: 'เริ่มต้น (Basic)',
    basicPlanDesc: 'เพิ่มการเข้าถึงขั้นพื้นฐานสำหรับการเปิดรับสมัครงานทั่วไป',
    basicPriceUnit: '/ ประกาศ',
    daysListing30: 'ระยะเวลาประกาศ 30 วัน',
    standardSearchPlacement: 'แสดงผลบนการค้นหาแบบทั่วไป',
    applicantTrackingIntegration: 'ระบบคัดกรองผู้สมัครในตัว',
    proPlanTitle: 'โปร (Pro)',
    proPlanDesc: 'เพิ่มโอกาสในการหาผู้สมัครในตำแหน่งสำคัญเป็นพิเศษ',
    proPriceUnit: '/ ประกาศ',
    recommendedBadge: 'แนะนำ',
    daysListing60: 'ระยะเวลาประกาศ 60 วัน',
    featuredTagPlacement: 'ป้ายกำกับ \'งานแนะนำ\' เพื่อการจัดอันดับที่ดีที่สุด',
    emailMatchingCandidates: 'ส่งอีเมลแจ้งเตือนถึงผู้สมัครที่มีทักษะตรงกันโดยตรง',
    socialMediaPromotion: 'โปรโมตผ่านช่องทางโซเชียลมีเดียของแพลตฟอร์ม',
    enterprisePlanTitle: 'องค์กร (Enterprise)',
    enterprisePlanDesc: 'โซลูชันแบบกำหนดเองสำหรับการสรรหาพนักงานจำนวนมาก',
    enterprisePrice: 'กำหนดเอง',
    unlimitedDurationOptions: 'ตัวเลือกระยะเวลาการลงประกาศแบบยืดหยุ่น',
    dedicatedAccountManager: 'ผู้จัดการบัญชีผู้ใช้ส่วนตัวคอยดูแล',
    customBrandingProfile: 'เพิ่มแบรนด์ของบริษัทคุณบนหน้าโปรไฟล์',
    advancedApiAccess: 'เข้าถึง API ขั้นสูงสำหรับการเชื่อมต่อระบบภายนอก',
    selectPlanBtn: 'เลือกแผนนี้',
    contactSalesBtn: 'ติดต่อฝ่ายขาย',
    trustedByLeaders: 'ได้รับความไว้วางใจจากบริษัทชั้นนำ',

    // Seeker / Employer Login & Register Pages Extras
    seekerLoginSubtitle: 'เข้าสู่ระบบด้วยชื่อผู้ใช้งาน และรหัสผ่านเพื่อหางาน',
    seekerRegisterSubtitle: 'สร้างบัญชีใหม่เพื่อเริ่มต้นส่งใบสมัครงาน',
    employerLoginSubtitle: 'เข้าสู่ระบบเพื่อจัดการประกาศรับสมัครงานและผู้สมัครของคุณ',
    employerRegisterSubtitle: 'สมัครสมาชิกองค์กรเพื่อเริ่มลงประกาศงาน',
    usernamePlaceholder: 'ชื่อผู้ใช้งาน (Username)',
    passwordPlaceholder: 'รหัสผ่าน (Password)',
    fullNamePlaceholder: 'ชื่อ - นามสกุล',
    emailPlaceholder: 'อีเมล (Email)',
    companyPlaceholder: 'ชื่อบริษัท (Company Name)',
    hrNamePlaceholder: 'ชื่อผู้ติดต่อ (HR / ผู้สรรหา)',
    passwordMinPlaceholder: 'รหัสผ่าน (อย่างน้อย 8 ตัวอักษร)',
    rememberMe: 'จดจำฉัน',
    forgotPassword: 'ลืมรหัสผ่าน?',
    orRegisterWith: 'หรือสมัครด้วย',
    registerHere: 'สมัครสมาชิกที่นี่',
    loginHere: 'เข้าสู่ระบบที่นี่',
    loginBtnText: 'เข้าสู่ระบบ',
    registerBtnText: 'สมัครสมาชิก',
    loginErrorText: 'เกิดข้อผิดพลาดในการเข้าสู่ระบบ',
    registerErrorText: 'เกิดข้อผิดพลาดในการสมัครสมาชิก',
    googleConnectionError: 'เกิดข้อผิดพลาดในการเชื่อมต่อกับ Google',
    passwordAdvice1: 'รหัสผ่านต้องมีความยาวอย่างน้อย 8 ตัวอักษร',
    passwordAdvice2: 'ต้องประกอบด้วยตัวอักษรพิมพ์เล็ก - พิมพ์ใหญ่ ผสมกับอักษรพิเศษหรือตัวเลข',
    passwordAdvice3: 'หลีกเลี่ยงการใช้ชื่อ วันเกิด เลขบัตรประชาชน หรือข้อมูลส่วนตัว',
    passwordAdvice4: 'ควรเปลี่ยนรหัสผ่านทุก 6 เดือนเพื่อความปลอดภัย',
    employerTermsTitle: 'ข้อกำหนดสำหรับผู้ประกอบการ :',
    employerTerms1: 'ต้องเป็นบริษัทหรือองค์กรที่จดทะเบียนถูกต้องตามกฎหมาย',
    employerTerms2: 'ระบุข้อมูลบริษัทและอีเมลติดต่อสำหรับการสรรหาบุคลากรตามจริง',
    employerTerms3: 'การเผยแพร่ประกาศรับสมัครงานจะต้องไม่ขัดต่อกฎหมายและศีลธรรมอันดี',

    // Company Details
    companyNotFound: 'ไม่พบข้อมูลบริษัท',
    noData: 'ไม่พบข้อมูล',
    companyNoName: 'บริษัทไม่ระบุชื่อ',
    companyImageMock: '1154 * 270 รูปบริษัท',
    hrContact: 'ผู้ติดต่อ: คุณ {name} (HR)',
    mockAddress: 'เลขที่ 1 หมู่ 6 ต.กำแพงแสน อ.กำแพงแสน จ.นครปฐม 73140',
    clickableLink: '(กดเพื่อส่งอีเมล)',
    aboutCompanyLabel: 'เกี่ยวกับบริษัท :',
    companyAboutDesc: 'เป็นผู้นำด้านการให้บริการและพัฒนาซอฟต์แวร์เทคโนโลยีสรรหาบุคลากรคุณภาพเพื่อเติบโตไปด้วยกัน',
    businessTypeLabel: 'ประเภทธุรกิจ :',
    businessTypeVal: 'เทคโนโลยี / ไอที',
    websiteLabel: 'เว็บไซต์ :',
    websiteVal: 'www.example.com',
    companyAddressLabel: 'ที่อยู่บริษัท :',
    mockAddressShort: 'นครปฐม, ประเทศไทย',
    welfareLabel: 'สวัสดิการ :',
    welfareBonus: 'โบนัสเดือนละล้านกีบ',
    transportTitle: 'การเดินทาง',
    mrtLabel: 'สถานีรถไฟฟ้าใกล้เคียง :',
    mrtVal: 'MRT เป้าแตก ทางออกประตู 3',
    busLabel: 'ป้ายรถ :',
    busVal: 'กำแพงแสน',
    mockMap: 'แผนที่จำลอง',
    companyJobs: 'ประกาศงานของบริษัท',
    noCompanyJobs: 'ไม่มีประกาศงานในขณะนี้',
  },
  en: {
    // Nav
    home: 'Home',
    findJobs: 'Find Jobs',
    employerPortal: 'Employer Portal',
    login: 'Login',
    register: 'Register',
    logout: 'Log Out',
    dashboard: 'Dashboard',
    createJob: 'Post Job',
    history: 'Job History',
    pricing: 'Pricing Plans',
    seekerPortal: 'Job Seeker',
    langToggle: 'TH',

    // Home
    heroTitle: 'Discover Your Dream Career Today',
    heroSubtitle: 'Connecting talented people with leading companies across the country',
    searchPlaceholder: 'Job title, company, or keywords...',
    searchBtn: 'Search Jobs',
    popularSearches: 'Popular Searches:',
    recentJobs: 'Recent Job Openings',
    viewDetails: 'View Details',
    fullTime: 'Full Time',
    partTime: 'Part Time',
    contract: 'Contract',
    internship: 'Internship',

    // Search
    searchTitle: 'Search Results',
    filterTitle: 'Filters',
    filterLocation: 'Job Location',
    filterCategory: 'Job Category',
    filterWorkType: 'Work Place Type',
    filterSalary: 'Min Salary (THB)',
    all: 'All',
    applyBtn: 'Apply Now',
    noJobsFound: 'No jobs found matching your search.',
    expectedSalary: 'Expected Salary',
    salaryUnit: 'THB / month',

    // Job Details
    jobDescription: 'Job Description',
    requirements: 'Requirements',
    salary: 'Salary',
    negotiable: 'Negotiable',
    postedDate: 'Posted on',
    backToSearch: 'Back to Search',
    aboutCompany: 'About the Company',
    viewCompanyProfile: 'View Company Profile',
    salaryRange: 'Salary Range',

    // Employer Dashboard
    activeJobs: 'Active Listings',
    totalApplicants: 'Total Applicants',
    interviews: 'Scheduled Interviews',
    statsSummary: 'Your Job Posting Statistics Overview',
    manageJobs: 'Manage Your Job Postings',
    jobTitle: 'Job Title',
    applicantsCount: 'Applicants',
    status: 'Status',
    actions: 'Actions',
    viewApplicants: 'Applicants',
    dashboardOverview: 'Employer Dashboard',
    unreadMessages: 'Unread Messages',

    // Employer Applications
    applicantsFor: 'Applicants for',
    applicantName: 'Applicant Name',
    applicantEmail: 'Email',
    applicationDate: 'Applied Date',
    resumeTitle: 'Application Resume',
    changeStatus: 'Change Status',
    statusPending: 'Pending',
    statusInterview: 'Interviewing',
    statusRejected: 'Rejected',
    noApplicants: 'No applicants for this job yet.',
    viewResumeBtn: 'View Resume',
    closeModal: 'Close',

    // Seeker Login/Register
    loginTitleSeeker: 'Job Seeker Login',
    registerTitleSeeker: 'Job Seeker Registration',
    loginTitleEmployer: 'Employer Login',
    registerTitleEmployer: 'Employer Registration',
    username: 'Username',
    password: 'Password',
    emailLabel: 'Email',
    fullNameLabel: 'Full Name',
    companyLabel: 'Company Name',
    orLoginWith: 'Or connect with',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    registerLink: 'Register here',
    loginLink: 'Login here',
    loginBtn: 'Log In',
    registerBtn: 'Sign Up',

    // Apply Wizard
    applyWizardTitle: 'Job Application - Resume Builder',
    wizardStep1: 'Resume Language',
    wizardStep2: 'Resume Details',
    wizardStep3: 'Application Status',
    thMode: 'Thai Resume Mode',
    enMode: 'English Resume Mode',
    thModeDesc: 'Fill application details in Thai to apply for local positions',
    enModeDesc: 'Fill application details in English for multinational or global companies',
    next: 'Next',
    back: 'Back',
    submitApplication: 'Save & Submit Application',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    targetedJobTitle: 'Expected Job Title / Career Objective',
    aboutMe: 'About Me (Short Introduction)',
    contactInfo: 'Contact Information',
    phone: 'Phone Number',
    address: 'Current Address',
    email: 'Contact Email',
    socialProfiles: 'Social Profiles (Optional)',
    workExperience: 'Work Experience',
    company: 'Company / Organization',
    position: 'Position',
    duration: 'Duration (e.g. 2023 - Present)',
    workDesc: 'Work Description / Key Accomplishments',
    addExperience: 'Add Experience',
    education: 'Education History',
    school: 'School / University',
    degree: 'Degree / Major (e.g. Bachelor in Computer Science)',
    gradYear: 'Graduation Year',
    addEducation: 'Add Education',
    skills: 'Skills & Expertise',
    techSkills: 'Technical Skills / Tools (comma-separated)',
    softSkills: 'Soft Skills / Personal Traits (comma-separated)',
    languages: 'Languages',
    langLevel: 'Proficiency Level (e.g., Native, Fluent, Intermediate)',
    langRating: 'Rating (1-5 stars)',
    addLanguage: 'Add Language',
    saveProfileOnly: 'Save Resume Only (No apply)',
    submitSuccess: 'Application Submitted!',
    successDesc: 'Your resume has been successfully saved, and your application was sent to the employer. You can expect a response via your email or phone.',
    backToJobs: 'Back to Find Jobs',

    // Employer Create Job
    postNewJob: 'Post a New Job',
    postJobDesc: 'Provide complete details about the job, benefits, and requirements for the best results.',
    locationPlaceholder: 'e.g., Bangkok, Chiang Mai (or Remote)',
    departmentLabel: 'Department (Optional)',
    salaryMinLabel: 'Min Salary (THB)',
    salaryMaxLabel: 'Max Salary (THB)',
    workTypeLabel: 'Work Place Type',
    publishBtn: 'Publish Job Posting',
    saveDraftBtn: 'Save as Draft',
    categoryLabel: 'Job Category',
    locationLabel: 'Job Location',
    descriptionLabel: 'Job Description / Responsibilities',
    requirementsLabel: 'Candidate Requirements / Skills',
    successCreateJob: 'Job posting created successfully!',

    // Employer History & Pricing
    historyTitle: 'All Published Job Postings',
    active: 'Active',
    draft: 'Draft',
    editBtn: 'Edit',
    deleteBtn: 'Delete',
    pricingTitle: 'Employer Plans & Pricing',
    pricingDesc: 'Choose the best plan to find top tier talent for your business.',
    freePlan: 'Free Starter Plan',
    premiumPlan: 'Premium Pro Plan',
    enterprisePlan: 'Enterprise Plan',
    priceFree: '฿0',
    pricePremium: '฿1,490',
    priceEnterprise: '฿4,900',
    priceUnit: '/ month',
    choosePlan: 'Choose Plan',
    unlimitedJobs: 'Unlimited job postings',
    candidateMatch: 'AI candidate matches recommendation',
    statsView: 'Advanced visual views stats analytics',

    // Employer Dashboard Extras
    welcomeBack: 'Welcome back, ',
    recruitmentToday: 'Here is what is happening with your recruitment today.',
    totalActiveJobs: 'TOTAL ACTIVE JOBS',
    newApplicants7Days: 'NEW APPLICANTS (last 7 days)',
    recentApplicantsTitle: 'Recent Applicants',
    viewAll: 'View All',
    nameCol: 'NAME',
    roleCol: 'ROLE',
    dateCol: 'DATE',
    hiringFunnelTitle: 'Hiring Funnel',
    appliedStage: 'APPLIED',
    screenedStage: 'SCREENED',
    interviewedStage: 'INTERVIEWED',
    offeredStage: 'OFFERED',
    quickActionsTitle: 'QUICK ACTIONS',
    postAJobBtn: 'Post a Job',
    scheduleInterviewBtn: 'Schedule Interview',
    viewReportsBtn: 'View Reports',
    activePostingsTitle: 'Active Postings',
    noActiveJobsFound: 'No active jobs found.',
    applicantsCountUpper: 'APPLICANTS',
    interviewsCountUpper: 'INTERVIEWS',
    boostTitle: 'Boost Your Visibility',
    boostDesc: 'Get your job postings in front of 3x more qualified candidates with our premium placement options.',
    exploreOptions: 'Explore Advertising Options',

    // Employer Create Job Extras
    postNewJobTitle: 'Post a New Job',
    postNewJobDesc: 'Fill in the details below to create a new job listing.',
    errorLabel: 'Error',
    basicDetails: 'Basic Details',
    jobTitleInput: 'JOB TITLE',
    jobTitlePlaceholder: 'e.g. Senior Software Engineer',
    categoryInput: 'CATEGORY',
    selectCategory: 'Select a category',
    locationInput: 'LOCATION',
    locationInputPlaceholder: 'e.g. San Francisco, CA or Remote',
    workTypeInput: 'WORK TYPE',
    onSite: 'On-site',
    hybridWork: 'Hybrid Work',
    remoteWork: 'Work from Home',
    minSalaryInput: 'MINIMUM SALARY (THB)',
    maxSalaryInput: 'MAXIMUM SALARY (THB)',
    salaryMinPlaceholder: 'e.g. 30000',
    salaryMaxPlaceholder: 'e.g. 50000',
    descriptionAndRequirements: 'Description & Requirements',
    jobDescriptionInput: 'JOB DESCRIPTION',
    jobDescPlaceholder: 'Describe the role, responsibilities, and team...',
    requirementsInput: 'REQUIREMENTS',
    requirementsPlaceholder: 'List the skills, experience, and qualifications needed...',
    publishingLabel: 'Processing...',
    listingStatusTitle: 'Listing Status',
    draftBadge: 'Draft',
    draftStatusDesc: 'Your job will not be visible to candidates until you hit \'Publish\'.',
    proTipsTitle: 'Pro Tips',
    proTip1: 'Be specific with your job title to attract the right candidates.',
    proTip2: 'Include salary ranges if possible, listings with salaries get 30% more applicants.',
    proTip3: 'Keep requirements realistic and focus on essential skills.',

    // Employer History Extras
    jobPostingHistoryTitle: 'Job Posting History',
    managePostingsDesc: 'Manage your current and past job postings.',
    postNewJobBtn: 'Post a New Job',
    searchHistoryPlaceholder: 'Search by job title or location...',
    filterBtn: 'Filter',
    postedDateCol: 'POSTED DATE',
    loadingJobsText: 'Loading jobs...',
    noJobsHistoryFound: 'No jobs found.',
    confirmDeleteJob: 'Are you sure you want to delete this job?',

    // Employer Pricing Extras
    pricingHeaderTitle: 'Accelerate Your Hiring Process',
    pricingHeaderDesc: 'Choose the advertising plan that fits your recruitment needs. Reach top tier candidates faster with our targeted promotional tools.',
    basicPlanTitle: 'Basic',
    basicPlanDesc: 'Essential visibility for standard hiring needs.',
    basicPriceUnit: '/post',
    daysListing30: '30-day listing duration',
    standardSearchPlacement: 'Standard search placement',
    applicantTrackingIntegration: 'Applicant tracking integration',
    proPlanTitle: 'Pro',
    proPlanDesc: 'Maximum exposure for critical roles.',
    proPriceUnit: '/post',
    recommendedBadge: 'Recommended',
    daysListing60: '60-day listing duration',
    featuredTagPlacement: 'Featured Tag placement',
    emailMatchingCandidates: 'Targeted email to matching candidates',
    socialMediaPromotion: 'Social Media Promotion',
    enterprisePlanTitle: 'Enterprise',
    enterprisePlanDesc: 'Custom solutions for volume hiring.',
    enterprisePrice: 'Custom',
    unlimitedDurationOptions: 'Unlimited listing duration options',
    dedicatedAccountManager: 'Dedicated Account Manager',
    customBrandingProfile: 'Custom branding on employer profile',
    advancedApiAccess: 'Advanced API access',
    selectPlanBtn: 'Select Plan',
    contactSalesBtn: 'Contact Sales',
    trustedByLeaders: 'Trusted by industry leaders',

    // Seeker / Employer Login & Register Pages Extras
    seekerLoginSubtitle: 'Log in with your username and password to find jobs',
    seekerRegisterSubtitle: 'Create a new account to start applying for jobs',
    employerLoginSubtitle: 'Log in to manage your job postings and candidates',
    employerRegisterSubtitle: 'Create an account to start posting job vacancies',
    usernamePlaceholder: 'username',
    passwordPlaceholder: 'password',
    fullNamePlaceholder: 'Full Name',
    emailPlaceholder: 'Email',
    companyPlaceholder: 'Company Name',
    hrNamePlaceholder: 'HR Contact Name',
    passwordMinPlaceholder: 'Password (Min 8 characters)',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    orRegisterWith: 'Or sign up with',
    registerHere: 'Register here',
    loginHere: 'Login here',
    loginBtnText: 'Log In',
    registerBtnText: 'Sign Up',
    loginErrorText: 'An error occurred during login',
    registerErrorText: 'An error occurred during registration',
    googleConnectionError: 'Failed to connect with Google',
    passwordAdvice1: 'Password must be at least 8 characters long.',
    passwordAdvice2: 'Must contain mixed case letters (upper/lower) and symbols/numbers.',
    passwordAdvice3: 'Avoid using names, birthdates, ID numbers, or personal info.',
    passwordAdvice4: 'Change your password every 6 months for better security.',
    employerTermsTitle: 'Employer Terms & Conditions:',
    employerTerms1: 'Must be a legally registered business or organization.',
    employerTerms2: 'Provide authentic company details and contact emails for recruitment.',
    employerTerms3: 'Job postings must comply with local labor regulations and policies.',

    // Company Details
    companyNotFound: 'Company not found',
    noData: 'No data found',
    companyNoName: 'Unnamed Company',
    companyImageMock: '1154 * 270 Company Cover',
    hrContact: 'Contact: {name} (HR)',
    mockAddress: '1 Moo 6, Kamphaeng Saen, Kamphaeng Saen, Nakhon Pathom 73140',
    clickableLink: '(Click to send email)',
    aboutCompanyLabel: 'About Company:',
    companyAboutDesc: 'A leading technology and recruitment solutions provider, matching quality talent with growth opportunities.',
    businessTypeLabel: 'Business Type:',
    businessTypeVal: 'Technology / IT',
    websiteLabel: 'Website:',
    websiteVal: 'www.example.com',
    companyAddressLabel: 'Company Address:',
    mockAddressShort: 'Nakhon Pathom, Thailand',
    welfareLabel: 'Welfare / Benefits:',
    welfareBonus: 'Bonus of 1 million Kip per month',
    transportTitle: 'Transportation',
    mrtLabel: 'Nearby Transit:',
    mrtVal: 'MRT Paotaek, Exit 3',
    busLabel: 'Bus Stop:',
    busVal: 'Kamphaeng Saen',
    mockMap: 'Mock Map',
    companyJobs: 'Company Job Postings',
    noCompanyJobs: 'No job openings at this time',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_lang') || 'th';
  });

  useEffect(() => {
    localStorage.setItem('app_lang', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'th' ? 'en' : 'th'));
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
